### ISSUE TITLE
guru callers failed

### ISSUE THREAD

**Issue by jostyee** [liuhewei/gotools-sublime#17]
my project.sublime-project settings:
```
{
	"folders":
	[
		{
			"path": "/Users/me/dev/go/src/github.com/jostyee/test"
		}
	],

	"settings": {
	    "golang": {

	      // A list of GOPATH for this project
	      // refer to github.com/golang/sublime-config
	      "GOPATH": "/Users/me/dev/go",

	      // A list of PATH for this project
	      // refer to github.com/golang/sublime-config
	      //"PATH": "C:\\Users\\jsmith\\go\\bin",

	      // The root package (or namespace) of a project.
	      "project_package": "github.com/go-playground/log"
	    }
	  }
}
```

But the guru callers command throws exception:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "gotools_guru in /Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Golang Tools Integration.sublime-package", line 31, in run
TypeError: 'NoneType' object is not iterable
```

**Comment by liuhewei** [comment]
"Guru callers" need add a "build_packages" config item into your project settings. Just like:

```
            "build_packages":
            [
                ""
            ],
            "project_package": "leetcode/security"
```

You can also refer to this [ExampleProject](https://github.com/liuhewei/gotools-sublime/blob/master/ExampleProject.sublime-project).

And, you can open the "debug" flag in Golang config to check the details in console: Preferences -> Package Settings -> Golang Config, add: `"debug_enabled": true`

**Comment by jostyee** [comment]
@liuhewei still has an issue:

```
GoTools: DEBUG: spawning process...
GoTools: DEBUG:     command:     /Users/me/dev/go/bin/guru -scope github.com/go-playground/.../ callers /Users/me/dev/go/src/github.com/go-playground/test/main.go:#4133
GoTools: DEBUG: process returned (1) in 0 seconds
GoTools: DEBUG: stderr:
cannot find package "github.com/go-playground/..." in any of:
    /usr/local/Cellar/go/1.7.3/libexec/src/github.com/go-playground/... (from $GOROOT)
    /Users/me/dev/go/src/github.com/go-playground/... (from $GOPATH)
guru: no initial packages were loaded

GoTools: DEBUG: guru callers output: 
GoTools: Guru error:
cannot find package "github.com/go-playground/..." in any of:
    /usr/local/Cellar/go/1.7.3/libexec/src/github.com/go-playground/... (from $GOROOT)
    /Users/me/dev/go/src/github.com/go-playground/... (from $GOPATH)
guru: no initial packages were loaded
```

project settings:

```
{
    "folders":
    [
        {
            "path": "."
        }
    ],

    "settings": {
        "golang": {

            // A list of GOPATH for this project
            // refer to github.com/golang/sublime-config
            //"GOPATH": "/Users/me/dev/go",

            // A list of PATH for this project
            // refer to github.com/golang/sublime-config
            //"PATH": "C:\\Users\\jsmith\\go\\bin",

            "build_packages":
            [
                ""
            ],

            // The root package (or namespace) of a project.
            "project_package": "github.com/go-playground/..."
        }
    }
}
```

guru support ... but gotools concat scope flag value incorrectly, it should be `-scope github.com/go-playground/...` w/o the suffix `/`

**Comment by jostyee** [comment]
https://github.com/alvarolm/GoGuru has a `"goguru_use_current_package" : true` configuration which could be very useful as well.

**Comment by liuhewei** [comment]
@jostyee Plz check if this commit is OK for you: https://github.com/liuhewei/gotools-sublime/commit/762926e94e8a804371de165b7c13ad122de29218

I changed "build_packages" to be optional, so you can ignore this config item in your case above.

**Comment by jostyee** [comment]
@liuhewei it works now, thx a lot.
but I still don't understand what build_packages for? there's no documentation on it

```
Pointer analysis scope: some queries involve pointer analysis, a technique for answering questions of the form “what might this pointer point to?”.  It is usually too expensive to run pointer analysis over all the packages in the workspace, so these queries require an additional configuration parameter called the scope, which determines the set of packages to analyze.  Set the scope to the application (or set of applications---a client and server, perhaps) on which you are currently working.  Pointer analysis is a whole-program analysis, so the only packages in the scope that matter are the main and test packages.

The scope is typically specified as a comma-separated set of packages, or wildcarded subtrees like github.com/my/dir/...; consult the specific documentation for your editor to find out how to set and vary the scope.
```

**Comment by liuhewei** [comment]
@jostyee Actually, these codes come from the old Gotools sublime-plugin. "build_packages" is used for setting "the set of packages to analyze". The reason is just like what you copied: for narrow the scope of guru's code analysis.

It can be an advanced configuration. I've seen your PR for easier configuration. Thanks:)

**Comment by jostyee** [comment]
@liuhewei still can't figure out the difference between `project_package` and `build_packages`.

furthermore, can gotools integrates https://github.com/alvarolm/GoGuru and https://github.com/alvarolm/GoRename instead of implement its own?

**Comment by liuhewei** [comment]
project_package is the common path, and build_packages is the real packages "imported" in code. I assume it's the reason, since the code is inherited from ironcladlou/GoTools.

It's not bad to integrate alvarolm's GoGuru and GoRename, but I recently don't have the time to try to migrate them. As a simplest way, you can add two flags to disable gotools' rename and guru functions, and then use alvarolm's instead. Just like: add a judgement in https://github.com/liuhewei/gotools-sublime/blob/master/gotools_guru.py#L12

I'm also happy to accept a PR for this integration if you're interested in this -:)

**Comment by jostyee** [comment]
Thanks for explaining, currently I'm unfamiliar with neither python nor sublime text plugin dev, may have a look into it later.
