### ISSUE TITLE
spit out error info to the console

### ISSUE THREAD

**Issue by alvarolm** [liuhewei/gotools-sublime#3]
for example when  an oracle call and fails, in the info bar shows: 

`GTools: oracle call failed (exit code)`

then briefly disapears, leaving the user with no clue of what went wrong.

https://github.com/liuhewei/gotools-sublime/pull/4
https://github.com/liuhewei/gotools-sublime/pull/5

**Comment by liuhewei** [comment]
Right, we can do this for showing errors even if "debug_enable" is set "false". BTW, thanks for your PR :)
